### ISSUE TITLE
Skip old migrations

### ISSUE THREAD

**Issue by benoittgt** [fatkodima/online_migrations#12]
Hello

When adding online_migrations on an old project. I have to change previous and old migrations when the database was not populated so without any risk of issue. Is it possible to make check on migration only on migration after a specific date? 

I can work on this PR if needed.

**Comment by fatkodima** [comment]
Hi. I think, `start_after` config option is what you are looking for - https://github.com/fatkodima/online_migrations#existing-migrations ?

**Comment by benoittgt** [comment]
Oups sorry. It's perfect.
