### ISSUE TITLE
Integration with CI

### ISSUE THREAD

**Issue by berniechiu** [fatkodima/online_migrations#2]
## Description

Hi @fatkodima, thanks for this nice gem, currently we've used `rails db:structure:load` for the CI integration/tests, which kind of avoid the checking migrations created from other team members, is it possible to check the new migrations manually from a rake tasks? Thanks!

**Comment by fatkodima** [comment]
Hi @berniechiu. Thank you for kind words ❤️. 

Unfortunately, this is not possible. This gem works by hooking into the process of running migrations, so to trigger checks - you need to run migrations.
