### ISSUE TITLE
Multiple assignments to same column error when trying to do a rename

### ISSUE THREAD

**Issue by jensljungblad** [fatkodima/online_migrations#22]
Trying to do the basic rename operation:

```ruby
# initializer
OnlineMigrations.config.column_renames = {
  "users" => {
    "old" => "new"
  }
}

# migration
initialize_column_rename(:users, :old, :new)
```

It creates the view, I can see it in the schema alright (using `structure.sql`).

However, if I try
```ruby
user = User.new
user.save
```

I get the following error: 
```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  multiple assignments to same column "old"
...
Caused by PG::SyntaxError: ERROR:  multiple assignments to same column "old"
```

The insert statement generated by Rails does look wrong: 
```sql
INSERT INTO users (old, new) VALUES (NULL, NULL)
```

Versions:
- Rails: 7.0.4.2 (newly generated, blank app)
- Postgres: 9.6 - 14.4
- `online_migrations`: 0.5.4

**Comment by fatkodima** [comment]
Interesting! Thank you for the report, looking into this.

**Comment by jensljungblad** [comment]
Thanks. Looking at the instructions for a rename operation, it's actually unclear when the old column is supposed to be removed.

**Comment by jensljungblad** [comment]
It looks like `initialize_column_rename` doesn't actually rename the column?

**Comment by jensljungblad** [comment]
Interesting. Did not get that error message when running the migration on a newly generated Rails 7 app. Will check why.

**Comment by jensljungblad** [comment]
Or ahh, the error message only appears if you try to do a regular `rename_column`, I see. Not if you do a `initialize_column_rename` without the setting enabled.

Are there any downsides to enabling this setting btw? Do you know why it was disabled for Rails 7?

**Comment by fatkodima** [comment]
That was done in https://github.com/rails/rails/pull/42769. The reasoning is explained in the CHANGELOG.

**Comment by jensljungblad** [comment]
Alright, sounds good!

**Comment by fatkodima** [comment]
Made some changes - https://github.com/fatkodima/online_migrations/commit/c13f826a5f421812cc87c17f598800f5e3c986c5

**Comment by popperur** [comment]
@fatkodima I wonder if it's alternative solution to remove the old column at this point? :
https://github.com/fatkodima/online_migrations/blob/master/lib/online_migrations/schema_cache.rb#L31
Adding a 
```columns.delete(old_column)```
line would fix the problem, no partial inserts are needed.. at least this is true for the second stage of the deploy I belive?

**Comment by fatkodima** [comment]
It is possible for the old code (with the old column name) to reload right after the VIEW was created (as part of the `initialize_column_rename`), and we need to have old column for old code to continue working.

A test case that demonstrates this - https://github.com/fatkodima/online_migrations/blob/f9eb505d7126b8d809eb319b9ff9a93e86da6937/test/schema_statements/renaming_column_test.rb#L58-L70

**Comment by popperur** [comment]
oh right. thank you!
