### ISSUE TITLE
Patched `add_foreign_key` helper does not pass on `deferrable` option

### ISSUE THREAD

**Issue by gstokkink** [fatkodima/online_migrations#24]
Hi,

First, thanks a lot for your hard work on this gem! It is very useful to us.

However, we ran into a snag when trying to add a deferred foreign key using the `add_foreign_key` helper. It appears that this gem alters this helper (for instance, to drop a pre-existing foreign key with the same name), but it doing so it breaks the `deferrable` option. Only way to add deferred foreign keys is by doing it by hand with a SQL statement. Less than ideal ofcourse ;-)

We use Rails 7.0.4.2.

**Comment by fatkodima** [comment]
Thank you for reporting! I completely missed this addition to rails 7.0. 

Pushed a fix. I will release a new version when the PR for other opened issue will be sent. You can point to the master branch until then.

**Comment by fatkodima** [comment]
Released a new version with this fix.

**Comment by gstokkink** [comment]
@fatkodima thanks! :)
