### ISSUE TITLE
Error at renaming a column if config.active_record.enumerate_columns_in_select_statements is set to true

### ISSUE THREAD

**Issue by popperur** [fatkodima/online_migrations#26]
I have a situation like this:

**application.rb:**

```ruby
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 7.0

    # Allow partial inserts
    config.active_record.partial_inserts = true

    # Enumerate columns in select statements
    config.active_record.enumerate_columns_in_select_statements = true
  end
```

**initializers/online_migrations.rb:**

```ruby
# initializer
OnlineMigrations.config.column_renames = {
  "users" => {
    "name" => "first_name"
  }
}
```

The first two parts of the rename operation have been already executed, and I have the migration file ready for the final part:

**20230214162556_finalize_rename.rb:**

```ruby
class FinalizeRename < ActiveRecord::Migration[7.0]
  def change
    finalize_column_rename :users, :name, :first_name
  end
end
```

Now I open a ruby console and execute
```ruby
> User.first
  User Load (0.3ms)  SELECT "users"."id", "users"."name", "users"."created_at", "users"."updated_at", "users"."first_name" FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<User:0x00000001120919c0 id: 1, name: "Joe", created_at: Tue, 14 Feb 2023 16:13:13.831911000 UTC +00:00, updated_at: Tue, 14 Feb 2023 16:13:13.831911000 UTC +00:00, first_name: "Joe"> 
```

Then I run the migration in a separate shell:
```
$ bin/rails db:migrate
== 20230214162556 FinalizeRename: migrating ===================================
-- finalize_column_rename(:users, :name, :first_name)
   -> 0.0309s
== 20230214162556 FinalizeRename: migrated (0.0335s) ==========================
```

Then I go back to the rails console and execute again:
```ruby
> User.first
  User Load (0.8ms)  SELECT "users"."id", "users"."name", "users"."created_at", "users"."updated_at", "users"."first_name" FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
/Users/popperur/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:783:in `exec_prepared': PG::UndefinedColumn: ERROR:  column users.name does not exist at character 22 (ActiveRecord::StatementInvalid)         
/Users/popperur/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:783:in `exec_prepared': ERROR:  column users.name does not exist at character 22 (PG::UndefinedColumn)
```

So as you can see, because of the `enumerate_columns_in_select_statements = true` setting it tries to execute the SQL with an old column. Without that setting the user object is retrieved properly.
I wonder if this is related to the `online_migrations` gem, and if yes, there is a solution for that? We use that setting to avoid `ActiveRecord::PreparedStatementCacheExpired` errors.

**Comment by fatkodima** [comment]
I think, the steps at https://github.com/fatkodima/online_migrations#renaming-a-column should be extended to:
...
4. Replace usages of the old column with a new column in the codebase
5. Ignore old column
  ```ruby
  class User < ApplicationRecord
    self.ignored_columns = [:name]
  end
  ``` 
6. Deploy
7. Remove the column rename config from step 1
8. Remove the column ignore from step 5
9. Remove the VIEW created in step 3 and finally rename the column:

```ruby
class FinalizeRenameUsersNameToFirstName < ActiveRecord::Migration[7.0]
  def change
    finalize_column_rename :users, :name, :first_name
  end
end
```
10. Deploy

What do you think?

**Comment by popperur** [comment]
Yeah, it seems that solves the issue.

**Comment by popperur** [comment]
@fatkodima I tested this out with version 0.7.1. It's still the same, if `config.active_record.enumerate_columns_in_select_statements = true` is used, then adding `self.ignored_columns = [:name]` is required, otherwise the described error can happen. So I guess the documentation could be extended with this info. What do you think?

**Comment by fatkodima** [comment]
Yes, this isn't closed because I am still going to update the docs. Is other patch working as expected?

**Comment by popperur** [comment]
> Is other patch working as expected?
Yes, that worked great! 🥳
