### ISSUE TITLE
Error at running the finalize_column_rename migration 

### ISSUE THREAD

**Issue by popperur** [fatkodima/online_migrations#27]
Similarly to https://github.com/fatkodima/online_migrations/issues/26, this issue happens after running the `finalize_column_rename` migration, but before deploying the final code changes. Sentry logged the following error:

```
ActiveRecord::StatementInvalid /organizations
PG::UndefinedTable: ERROR: relation "organizations_column_rename" does not exist LINE 9: WHERE a.attrelid = '"organizations_column_rename"'::regclas... ^

PG::UndefinedTable
ERROR:  relation "organizations_column_rename" does not exist
LINE 9:  WHERE a.attrelid = '"organizations_column_rename"'::regclas...
                            ^
Crashed in non-app: activerecord (7.0.4.2) lib/active_record/connection_adapters/postgresql/database_statements.rb in exec
Called from: online_migrations (0.5.4) lib/online_migrations/schema_cache.rb in columns at line 20
Called from: activerecord (7.0.4.2) lib/active_record/connection_adapters/schema_cache.rb in block in columns_hash
lib/middleware/rewriter/middleware.rb in thread_safe_call at line 41
lib/middleware/rewriter/middleware.rb in call at line 25
Called from: sentry-rails (5.8.0) lib/sentry/rails/rescued_exception_interceptor.rb in call
lib/middleware/gcp_trace_middleware.rb in call at line 12
Called from: rack (2.2.6.2) lib/rack/method_override.rb in call
```

The mentioned line of the `online_migrations` gem is this:

<img width="840" alt="Screenshot 2023-02-14 at 23 48 18" src="https://user-images.githubusercontent.com/378323/218880820-1d5e0223-cebe-4773-9557-6f7d3bcf3717.png">

This is only a hunch, but maybe this issue happens because the previous line
```ruby
elsif renamed_columns.key?(table_name)
```
incorrectly retrieves `true`. The `renamed_columns` method has a caching that might cause the problem here. I could not verify yet, but maybe the remove of the cache would solve the problem, so that method could look like that:

```ruby
    def renamed_columns
      column_renames = OnlineMigrations.config.column_renames
      return {} if column_renames.blank?

      views = connection.views
      column_renames.select do |table_name, _|
        views.include?(table_name)
      end
    end
```

What do you think?

**Comment by fatkodima** [comment]
Can you describe the steps to reproduce the issue? That behavior is a little weird, since `columns` are cached in the model class - https://github.com/rails/rails/blob/4345e84587f4a6a92214a23ca3d85a403d9087df/activerecord/lib/active_record/model_schema.rb#L420-L423 and should be already loaded after the `finalize_column_rename` was ran.

**Comment by popperur** [comment]
I haven't been able to reproduce it locally, unfortunately. This issue happened on our staging server when we run various API tests after the `finalize_column_rename` migration. I tried to replicate the environment we have up there, but something is clearly different because I don't get the error what occurred there. 
Sentry logged another similar error, but call stack didn't contain `schema_cache.rb` in that case:

```
ActiveRecord::StatementInvalid
PG::UndefinedTable: ERROR:  relation "organizations_column_rename" does not exist
LINE 5:           WHERE indrelid = '"organizations_column_rename"'::...
                                   ^
PG::UndefinedTable
ERROR:  relation "organizations_column_rename" does not exist
LINE 5:           WHERE indrelid = '"organizations_column_rename"'::...
                                   ^
Crashed in non-app: activerecord (7.0.4.2) lib/active_record/connection_adapters/postgresql/database_statements.rb in exec
app/controllers/api_controller/base.rb in current_organization at line 64
app/controllers/api_controller/base.rb in append_info_to_payload at line 91
Called from: actionpack (7.0.4.2) lib/action_controller/metal/instrumentation.rb in ensure in block in process_action
lib/middleware/rewriter/middleware.rb in thread_safe_call at line 41
lib/middleware/rewriter/middleware.rb in call at line 25
Called from: sentry-rails (5.8.0) lib/sentry/rails/rescued_exception_interceptor.rb in call
lib/middleware/gcp_trace_middleware.rb in call at line 12
Called from: rack (2.2.6.2) lib/rack/method_override.rb in call
```

I could not run further tests yet because we did a rollback. 
We didn't add the `self.ignored_columns` (mentioned in https://github.com/fatkodima/online_migrations/issues/26) yet, but I guess that wouldn't help here because the table name is the problem here.
Please let me know if you have some further ideas. Otherwise, we'll retry the migration soon, hopefully I'll gather more info.

**Comment by fatkodima** [comment]
Thank you for the follow up! 
It will definitely help if you could figure out the reproduction steps. But in either case, I will try to dive into it to find what would cause it.

**Comment by fatkodima** [comment]
Were you able to identify the problem? 
1. Do you use schema cache on staging? 2. And is your application eager loaded on staging?

**Comment by fatkodima** [comment]
So the problem is with caching, as you mentioned, I am 99% sure for this case.

What happened on staging: unless you are using schema cache, model's metadata (primary key, columns etc) is retrieved lazily on the first access of the model. The `renamed_columns` was cached on the first access to some other model (not `Organization`, in your case), probably `User` when authenticating. And `Organization` was not loaded yet. Then you ran `finalize_column_rename`, which removed the VIEW and tried to access `Organization` for the first time. Cached `renamed_columns` still thinks that there is a VIEW there, but there isn't this time. So bam 💥

**Comment by popperur** [comment]
@fatkodima thank you for the reply and sorry for the delayed response.
> Do you use schema cache on staging? 2. And is your application eager loaded on staging?

We don't use schema cache in production, and yes, the app is eager loaded on boot (`config.eager_load = true`)

Today I will give a try with your changes, I'll let you know how it went!

**Comment by popperur** [comment]
@fatkodima could you create a new build from these changes? I run into some issues with testing the pinned commit from github in our GCP environment.

**Comment by popperur** [comment]
@fatkodima UPDATE: I actually managed to make the pinned commit working, and it seems the changes fix the issue! 🙏Could you create a release from it? I'll run one more test with the final version.

**Comment by fatkodima** [comment]
Released a new version with this fix.
