### ISSUE TITLE
"undefined method `__raw_connection'" on rollback

### ISSUE THREAD

**Issue by noahfpf** [fatkodima/online_migrations#3]
When rolling back a migration (but not running the migration in the first place) with `rails db:rollback:primary`, we're getting the following error:

```
undefined method `__raw_connection' for #<ActiveRecord::Migration::CommandRecorder:0x0000aaaaf43894c0>
db/migrate/20220318210531_add_url_to_user.rb:3:in `change'
```

The migration file is:

```ruby
class AddUrlToUser < ActiveRecord::Migration[6.1]
  def change
    add_column(:user, :url, :string)
  end
end
```

The error is originating from:
https://github.com/fatkodima/online_migrations/blob/7e6159bc5b3df316512fb439ea8e73cb9c775fdf/lib/online_migrations/command_checker.rb#L578
where `connection` is an instance of `ActiveRecord::Migration::CommandRecorder` and apparently doesn't have a method named `__raw_connection`.

More details:
- `online_migrations`: 0.4.0
- `rails`: 6.1.4.7
- `config/initializers/online_migrations.rb` is mostly the defaults, other than setting `start_after`, `small_tables`, and `lock_timeout_limit`.

Any thoughts on what might be wrong before I dive in further?  What class is `connection` typically?

And thanks for the gem!  It looks super helpful to make our migrations safer.

**Comment by fatkodima** [comment]
Thank you for detailed reporting. Can you verify the latest changes on master fix you problem?

Happy to hear that you find this gem helpful 🤗

**Comment by noahfpf** [comment]
That fix works, thanks for implementing it so quickly! 🚀

**Comment by fatkodima** [comment]
Released a new version with that change.
