### ISSUE TITLE
Attempting to update `pg_catalog` when changing type of not null column w/o a default

### ISSUE THREAD

**Issue by solebared** [fatkodima/online_migrations#34]
When changing the type of a not null column _with_ a default, online_migrations is able to avoid having to `update pg_catalog ...` Which is great because privileges on that table are restricted in many environments. 

However, if the column in question does _not_ have a default, we drop into the [codepath](https://github.com/fatkodima/online_migrations/blob/d0c4114d64ebe1bb162a563ec9bfdbd01afa2622/lib/online_migrations/change_column_type_helpers.rb#L244) in `finalize_columns_type_change` that attempts to update pg_catalog.

A similar concern was raised in #21 but i believe the changes there addressed PK columns and those with defaults.

### Steps to recreate
1. On postgresql >= version 12, follow the steps to [change the type of a column](https://github.com/fatkodima/online_migrations#changing-the-type-of-a-column).
2. Use a column with `null: false` but without a default.
3. Run migrations (with `config.verbose_sql_logs = true`).
4. In stdout or logs, look for `UPDATE pg_catalog.pg_attribute`.

### Snippets from my testing
```bash
❯ postgres --version
postgres (PostgreSQL) 13.11
```

```ruby
  # first migration: changing `number` from `string` to `integer`
  # the original column is `null: false`
  def change
    initialize_column_type_change :some_numbers, :number, :integer
  end
```

Running the 'finalize' migration shows:
```log
D, [2023-09-23T23:43:47.667897 #24329] DEBUG -- :   TRANSACTION (0.0ms)  BEGIN /*application:Wrapbook*/
D, [2023-09-23T23:43:47.668343 #24329] DEBUG -- :    (0.2ms)  UPDATE pg_catalog.pg_attribute
SET attnotnull = true
WHERE attrelid = 'some_numbers'::regclass
  AND attname = 'number_for_type_change'
 /*application:Wrapbook*/
D, [2023-09-23T23:43:47.669486 #24329] DEBUG -- :    (0.2ms)  ALTER TABLE "some_numbers" DROP CONSTRAINT "chk_rails_0171ff2f52" /*application:Wrapbook*/
D, [2023-09-23T23:43:47.669940 #24329] DEBUG -- :   TRANSACTION (0.2ms)  COMMIT /*application:Wrapbook*/
```

This works on my local but fails in managed environments.

### Workaround
1. Force a default value in the initialize migration, eg:
    `initialize_column_type_change :some_numbers, :number, :integer, null: false, default: 0`
1. Add remaining migrations as prescribed.
1. Add an extra migration to drop the default after the 'cleanup' step, eg:
    `change_column_default :some_numbers, :number, nil`

While this a relatively easy workaround, i think the issue might be worth fixing because it can be a bit baffling when first encountered.

### Possible fix (?)
The comment [here](https://github.com/fatkodima/online_migrations/blob/d0c4114d64ebe1bb162a563ec9bfdbd01afa2622/lib/online_migrations/change_column_type_helpers.rb#L254-L256) speaks to the possibility of promoting the check constraint on PG >= 12, instead of attempting to update pg_catalog. Perhaps we need to implement that to cover this edge case?

I'd be happy to attempt that in a PR if you think that's the right direction.

Thanks for all your work on this very useful gem!

**Comment by fatkodima** [comment]
Hey, firstly, thank you for such a detailed report!

> The comment [here](https://github.com/fatkodima/online_migrations/blob/d0c4114d64ebe1bb162a563ec9bfdbd01afa2622/lib/online_migrations/change_column_type_helpers.rb#L254-L256) speaks to the possibility of promoting the check constraint on PG >= 12, instead of attempting to update pg_catalog. Perhaps we need to implement that to cover this edge case?

This seems like a way to go for me. Please, do open a PR.

**Comment by solebared** [comment]
@fatkodima , i have a draft up at #35 .

I need to do some testing to verify the 'promotion' doesn't lock the table, and look for the expected `DEBUG` statement, as [shown here](https://github.com/postgres/postgres/commit/bbb96c3704c041d139181c6601e5bc770e045d26#diff-a6c1d76839ac32d79c6a3c9767093d35cb983a2597d9b1f91676c71d020ca667R1095).

Sending your way for any initial feedback in the meantime. In particular, please see my comment on the test cases included.

Thanks!

**Comment by fatkodima** [comment]
Released a new version. Thanks for the fix!

**Comment by solebared** [comment]
Amazing, quick turnaround! 🥇 😍 🙏🏾 :).

Thanks again for all your work. And encouragement -- i learnt a lot from this issue and patch!
