### ISSUE TITLE
Ability to run custom cast logic in column type change

### ISSUE THREAD

**Issue by agrieser-healthie** [fatkodima/online_migrations#36]
Trying to convert a varchar column to integer results in the following error: `PG::UndefinedFunction: ERROR:  operator does not exist: integer <> character varying`

The `backfill_column_for_type_change` method takes a `type_cast_function` parameter, but the only example I can find using that passing in `jsonb`.

I have a varchar column that contains integer id references to another table, and want to change the column type from varchar to int. I realize `varchar` -> `int` is not a safe cast, but all of the data in the table is an integer, just stored as text.

Is there a way to use the change column type recipe for this, or does this need to be a a custom migration?

**Comment by fatkodima** [comment]
Hey, thanks for using this gem and for the report! It is not currently possible, but I can implement an ability to pass raw sql literals, so you can write something like: `type_cast_function: Arel.sql("column::integer")`.

Will explore this today/tomorrow and release a new version with this change.

**Comment by fatkodima** [comment]
Released a new version with this change.

**Comment by fatkodima** [comment]
It is not correctly serialized when saved to the database in the `jsonb` column, because it is `Arel.sql` instead of just string. I will take a look what I can do. Thanks for reporting!

**Comment by fatkodima** [comment]
Pushed a fix. Can you verify `master` works for you?

**Comment by fatkodima** [comment]
That comes from https://github.com/fatkodima/online_migrations/blob/c77f430fe931f4ce0046b3f0ab57b972b44839d8/lib/online_migrations/background_migrations/migration.rb#L35, but I currently didn't get how that is possible.

What value this query returns for the table where column is modified https://github.com/fatkodima/online_migrations/blob/c77f430fe931f4ce0046b3f0ab57b972b44839d8/lib/online_migrations/utils.rb#L126-L131?
