### ISSUE TITLE
Custom or Longer Statement Timeout for Migrations

### ISSUE THREAD

**Issue by berniechiu** [fatkodima/online_migrations#4]
## Description

Hi @fatkodima,

Not sure if you would like to elaborate more on those descriptions here:
https://github.com/fatkodima/online_migrations#migration-timeouts
https://github.com/ankane/strong_migrations/blob/master/README.md#good-7

For instance like concurrent indexing, the requirement for longer statement timeout might be needed since the fact that statement could run for quite a while on larger table, apart from the application level. I think this has already implemented as a good practice in few of the larger organizations and gems.

REF: 
https://gitlab.com/gitlab-org/gitlab-foss/-/blob/f21e655b61725b972ae80d584a66d6deb53a337d/lib/gitlab/database/migration_helpers.rb#L68
https://github.com/doctolib/safe-pg-migrations/blob/1ea078352413df201a4d410f5947ece1c67923fd/test/idempotent_statements_test.rb#L102-L124
https://github.com/ankane/strong_migrations#migration-timeouts

**Comment by fatkodima** [comment]
Hi @berniechiu,

Did you mean this
https://github.com/fatkodima/online_migrations/blob/8d8054751bf45293ab2cfc98c243cdef89cb3f41/lib/online_migrations/schema_statements.rb#L667-L672

?

**Comment by berniechiu** [comment]
Ah yeah! Thanks! Now I see that's already in the codebase
