### ISSUE TITLE
Index name too long error on finalize_column_type_change migration

### ISSUE THREAD

**Issue by agrieser-healthie** [fatkodima/online_migrations#44]
Index name 'index_blah' on table 'my_table' is too long; the limit is 63 characters

I think coming from here: https://github.com/fatkodima/online_migrations/blob/master/lib/online_migrations/change_column_type_helpers.rb#L446

Is it possible to reuse the name of the existing one, or if it's too long generate a shorter name? Or accept options?

**Comment by fatkodima** [comment]
Thanks for the report. Rails recently introduced a change to automatically shrink index names. I will take a look if we can reuse that.

**Comment by jjb** [comment]
wow!

**Comment by fatkodima** [comment]
Crap, yes. I will take a look.

**Comment by fatkodima** [comment]
Ah, nope, thats not related to the fix I pushed. You actually need to rename the index to include the column name in it.
What is the column's name you are trying to change type of?

**Comment by fatkodima** [comment]
I honestly can't recall why it was done this way. But, yeah, seems like this is not necessary. Pushed a fix to `master`.

**Comment by jjb** [comment]
wow!

**Comment by jjb** [comment]
https://github.com/fatkodima/online_migrations/commit/c77f430fe931f4ce0046b3f0ab57b972b44839d8
