### ISSUE TITLE
Question on 'Adding multiple foreign keys': why does adding multiple FKeys block reads on all involved tables?

### ISSUE THREAD

**Issue by wholien** [fatkodima/online_migrations#46]
The [Adding multiple foreign keys](https://github.com/fatkodima/online_migrations?tab=readme-ov-file#adding-multiple-foreign-keys) section writes:

> Adding multiple foreign keys in a single migration **blocks reads and writes on all involved tables** until migration is completed.

@fatkodima has [also written that adding a single foreign key is safe](https://github.com/ankane/strong_migrations/issues/170#issuecomment-1169416250):

> Adding a **single** foreign key when creating a table is safe, but adding **multiple** foreign keys is not, as you actually experienced. See https://github.com/fatkodima/online_migrations#adding-multiple-foreign-keys for the details.

1. Why does adding 2 foreign keys in the same `create_table` block reads and writes on all involved tables? Specifically, I'm surprised by the `blocks reads` part. I thought `SHARE ROW EXCLUSIVE` locks would be acquired for all involved tables, but that lock should not block reads.
2. why is adding more than 1 foreign key in a single migration unsafe, while adding exactly 1 foreign key is safe? Is it due to needing to acquire more locks on different tables, how the postgres lock queue works, and the migration block not finishing and releasing all acquired keys until all foreign keys are added? But waiting to finish and releasing keys are needed in the 1 foreign key case too, no?

**Comment by gstokkink** [comment]
I was wondering about this as well.

**Comment by fatkodima** [comment]
Thanks for opening the issue!

> Why does adding 2 foreign keys in the same create_table block reads and writes on all involved tables? Specifically, I'm surprised by the blocks reads part. I thought SHARE ROW EXCLUSIVE locks would be acquired for all involved tables, but that lock should not block reads.

Yes, you are actually correct regarding `blocks reads`, only writes are blocked.

> I was wondering about this as well. When a new table is created, there is no data yet to be validated. Hence, the amount of foreign keys created as part of the create_table statement shouldn't matter, right? Right now it allows a single foreign key, but not multiple.

There is no data yet, but PostgreSQL still acquires (`SHARE ROW EXCLUSIVE`) locks on all the referenced tables. To check, if the table has the correct column definition (like having some kind of uniqueness on it), for example.

 > why is adding more than 1 foreign key in a single migration unsafe, while adding exactly 1 foreign key is safe? Is it due to needing to acquire more locks on different tables, how the postgres lock queue works, and the migration block not finishing and releasing all acquired keys until all foreign keys are added? 

Yes, that is related to that we need to acquire locks on all the referenced tables and lock queues.

> But waiting to finish and releasing keys are needed in the 1 foreign key case too, no?

Yes, but in case of 1 foreign key, we need to acquire a lock only on 1 referenced table. 
But in case of multiple - on multiple. And while we try to acquire all the locks in this case, all the previously already acquired locks are blocking certain operations on their tables while we are trying to acquire the rest. Imagine trying to add 2 foreign keys to 2 busy tables at the same time.

Hope that helps.

**Comment by gstokkink** [comment]
Clear, thanks for the explanation 👍🏻

**Comment by wholien** [comment]
thanks for taking the time to answer!

> > But waiting to finish and releasing keys are needed in the 1 foreign key case too, no?
> 
> Yes, but in case of 1 foreign key, we need to acquire a lock only on 1 referenced table. But in case of multiple - on multiple. And while we try to acquire all the locks in this case, all the previously already acquired locks are blocking certain operations on their tables while we are trying to acquire the rest. Imagine trying to add 2 foreign keys to 2 busy tables at the same time.
> 
> Hope that helps.



re: the this part specifically:

I agree adding 2 FKs to 2 busy tables at the same time sounds like an unwise idea. 

Is there 0% risk when adding 1FK to 1 busy table? Is it just a mechanism of the queue? Or is there still potential for issues when adding 1 foreign key - albeit a far lower chance than when adding more than 1 foreign key?

thanks!

**Comment by fatkodima** [comment]
> Or is there still potential for issues when adding 1 foreign key - albeit a far lower chance than when adding more than 1 foreign key?

This.

**Comment by wholien** [comment]
> > Or is there still potential for issues when adding 1 foreign key - albeit a far lower chance than when adding more than 1 foreign key?
> 
> This.

just to confirm my logic - and sorry again for being a bit annoying. Just want to totally get my mental model correctly:


**when just adding 1 FK to a busy table:** 

1. the migration might wait in the queue until getting the lock -> while waiting, there is no effect on live traffic
2. once migration has the lock, it almost immediately is able to add and validate the new FK (since no data in the new table)

but when adding 2 or more FKs from busy tables:
1. migration again waits to get first lock on first table
2. once it has the first lock, it still has to wait for the lock on the 2nd busy table
3. while waiting on the 2nd busy table, because this migration has that first `SHARE ROW EXCLUSIVE` lock on the first table, the first table cannot be written to
3. writes/updates to the first table during this time cannot go through

**Comment by fatkodima** [comment]
Every point in both examples is right, except
> 1. the migration might wait in the queue until getting the lock -> while waiting, there is no effect on live traffic

There is actually effect on the live traffic. While waiting, the adding foreign key query tries to acquire `SHARE ROW EXCLUSIVE` lock and every other query that comes after that query with conflicting locks will be locked (that is everything except `SELECT` queries). Google for "postgresql locks queue" (example link - https://www.citusdata.com/blog/2018/02/15/when-postgresql-blocks/), if you are not familiar with the concept.
