### ISSUE TITLE
Undefined method  `cleanup_change_column_type_concurrently' 

### ISSUE THREAD

**Issue by vonchristian** [fatkodima/online_migrations#5]
I am currently following the [README](https://github.com/fatkodima/online_migrations#backfilling-data) to update a column from integer to bigint. Having an issue `undefined method cleanup_change_column_type_concurrently`  when running the migration. Thank you.

**Comment by fatkodima** [comment]
@vonchristian Thanks for report. I apologize, this is not the actual method's name. You should use `cleanup_column_type_change` instead. Updated the readme.
