### ISSUE TITLE
Clarity on lock retry behaviour inside and outside transactions

### ISSUE THREAD

**Issue by camallen** [fatkodima/online_migrations#50]
I'm seeking clarification about the lock retry behaviour when running the migration outside of a transaction. 

In [the docs](https://github.com/fatkodima/online_migrations/blob/master/docs/configuring.md#lock-timeout-retries) you explicitly state the retry behaviour when the migration runs inside a migration

> When statement within transaction fails - the whole transaction is retried.

However when running the migration without a transaction via `disable_ddl_transaction!` it's not clear in the docs but my assumption is that the LockRetrier does the same. E.g. in the [test code](https://github.com/fatkodima/online_migrations/blob/9cebfd00b870ab246e813d8109767ccaf10a7df6/test/lock_retrier_test.rb#L45) it shows the migration is retried by the LockRetrier mechanism (if set).

Can you please clarify the behaviour is as I assume. I'm happy to get a PR up to update the `configuring.md` doc as well.

**Comment by fatkodima** [comment]
Yes, your assumption is correct. Please do open a PR.

**Comment by ghiculescu** [comment]
Hmm, I'm not sure if https://github.com/fatkodima/online_migrations/blob/9cebfd00b870ab246e813d8109767ccaf10a7df6/test/lock_retrier_test.rb#L49 is as clear as it could be.

`$migrate_attempts` is only incremented once, [here](https://github.com/fatkodima/online_migrations/blob/9cebfd00b870ab246e813d8109767ccaf10a7df6/test/lock_retrier_test.rb#L17). After that, `add_column :users, :name, :string` tries, and fails.

The change in https://github.com/fatkodima/online_migrations/pull/51 implies that now  `add_column :users, :name, :string` will be retried. If that's the case, I would expect this test to have an infinite loop, or to have the lock be removed and the column cleanly added. If the latter is the intended behaviour, I think the test should assert that. But I think what's more likely is that there is no retrying happening at all in this test.

Given that, I think what the docs should say is:

> When a statement within transaction fails, the whole transaction is retried. If any statement fails when running outside a transaction (e.g. using `disable_ddl_transaction!`), that statement will not be retried.

@fatkodima @camallen what am I missing?

**Comment by fatkodima** [comment]
The `$migrate_attemps` is equal to 1, because we actually run the whole migration `change` method only once. It demonstrates, that we do not retry the whole transaction (because there is no even one). 
But we run `add_column` multiple times.

The runtime of the whole migration looks like this:
```ruby
def change
  $migrate_attemps += 1
  add_column ... => raises lock error
  add_column ... again.. => raises lock error again
end
```

**Comment by ghiculescu** [comment]
Ahhh now I see what's going on. https://github.com/fatkodima/online_migrations/blob/2040b8699e470e6dd29cc2be2daddb0b511b1bc5/lib/online_migrations/migration.rb#L27 is where each statement is wrapped with a lock retrier. Neat 👍
