### ISSUE TITLE
add_reference_concurrently with polymorphic option

### ISSUE THREAD

**Issue by brigidspeed23** [fatkodima/online_migrations#61]
Gem version: 0.19.4
Ruby version: 3.3.4
Rails version: 8.0.0.alpha

Hi !!

We're seeing some undesirable behaviour while running an add_reference_concurrently migration with the polymorphic flag enabled eg

```
class Btest1Migration < ActiveRecord::Migration[8.0]
  regions :all

  disable_ddl_transaction!

  def up
    add_reference_concurrently :automatic_break_templates, :pay_condition_settable, polymorphic: true
  end
end
```

When we run the migration the first time, it fails with error  `ERROR:  column "pay_condition_settable_type" does not exist`.

We can see from the raw SQL, that the migration only creates the _id column and isn't attempting to create the _type column:
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/70fd10e2-2bef-4ad3-8f57-b34f0e7869d1">

This is the first issue: creation column _type is not attempted before creation of index.

Checking the table schema at this point and both the _id and _type columns and the index have not been added (as expected for the migration failing).

Running the migration a second time, and it also fails with error `ERROR:  column "pay_condition_settable_type" does not exist`, however this time we can see from the raw SQL that the there is no attempt to create either the _id or _type column (although neither of these exist) prior to attempting to create the index:
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/f6bab739-38a8-4861-9be1-7c349f013ca4">

This is the second issue: inconsistent behaviour of the migration between subsequent runs.

The first issue might be a fairly simple bug fix, but we'd be interested if anyone has any thoughts or insight on the second issue as well.

Many thanks in advance !!

**Comment by fatkodima** [comment]
Thanks for reporting! Yeah, so this is a bug. And the whole operation should be idempotent, so subsequent runs should be no-ops.

I will fix it and release a new version tomorrow.

**Comment by fatkodima** [comment]
Can you please confirm that the changes from master actually fixes your problem? And so I will release a new version.

**Comment by fatkodima** [comment]
Released a new version with the fix.

**Comment by brigidspeed23** [comment]
@fatkodima I have tested with v0.19.5 and the issue is indeed resolved (both columns and index confirmed created successfully):

<img width="1416" alt="image" src="https://github.com/user-attachments/assets/c6b1c907-2f28-4852-be7f-791e498b4691">

Many thanks for the fast turn around - it was much appreciated !!
