### ISSUE TITLE
add_reference_concurrently creates "_type" column without explicitly saying polymorphic: true in migration: version 0.19.6

### ISSUE THREAD

**Issue by HafizSaad12** [fatkodima/online_migrations#63]
Hello,

I installed online_migration version "0.19.6", I was referencing columns and noticed that this "0.19.6" version creates "_type" although in migration there is no polymorphic: true option passed to "add_reference_concurrently" function.

**Migration File**
![image](https://github.com/user-attachments/assets/1a0b2efe-9d76-4f80-87e3-f08fb4607e2a)

**Console Preview**
![image](https://github.com/user-attachments/assets/b0ac0253-66c6-4c0b-9156-69acae2d90ae)

As I installed previous version: 0.19.5
There is no "_type" column added by migration. It is working as you expect.

**Comment by fatkodima** [comment]
Hello, 

Are you sure you use 0.19.6? It should be fixed currently - https://github.com/fatkodima/online_migrations/commit/a1cece4f1d8a0ceecfdb0d8446f20979e5ce2290

**Comment by HafizSaad12** [comment]
Yes,

I was sure but I checked it again, it did not create "_type" column maybe it was bundling caching issue.

Thanks
